# Site settings
title: Nicolas G. 
email: nicolasg@domain.com
description: "Simple site with posts by Nicolas G."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: nicolas_g
github_username:  nicolas-g

# Build settings
markdown: kramdown
permalink: pretty
